foreground            #c0caf5
background            #1a1b26
selection_foreground  none
selection_background  #283457

cursor                #c0caf5
cursor_text_color     #1a1b26

url_color             #7dcfff

active_border_color   #3d59a1
inactive_border_color #414868
bell_border_color     #e0af68

active_tab_foreground   #a9b1d6
active_tab_background   #24283b
inactive_tab_foreground #565f89
inactive_tab_background #16161e
tab_bar_background      #1a1b26

# black
color0   #16161e
color8   #565f89

# red
color1   #f7768e
color9   #ff899d

# green
color2   #9ece6a
color10  #9ece6a

# yellow
color3   #e0af68
color11  #e0af68

# blue
color4   #7aa2f7
color12  #7dcfff

# magenta
color5   #bb9af7
color13  #bb9af7

# cyan
color6   #1abc9c
color14  #2ac3de

# white
color7   #a9b1d6
color15  #c0caf5
